### ISSUE TITLE
Docs need to be updated for Bundler monorepo

### ISSUE THREAD

**Issue by joel-daros** [total-typescript/tsconfig#8]
The README is referring to the `"extends": "@total-typescript/tsconfig/bundler/dom/library-monorepo", // For a library in a monorepo` but this file seems to have been deleted from the repository.

**Comment by mattpocock** [comment]
This is an alias:

https://github.com/total-typescript/tsconfig/blob/main/package.json#L33

**Comment by haydn** [comment]
FYI, I've defaulted to using `"@total-typescript/tsconfig/bundler/dom"` in my projects because I've run into two places where tooling doesn't respect the app/library/library-monorepo aliases:

1. VSCode's option-click to follow link when viewing the `tsconfig.json`.
2. Both of these TypeScript coverage reporters hit errors:
   1. https://github.com/alexcanessa/typescript-coverage-report
   2. https://github.com/plantain-00/type-coverage

Maybe it's worthwhile just having duplicate files instead of aliases to maximise compatibility with tooling?
